force-app/main/default/objects/Lead/fields/Application_Source__c.field-meta.xml
<CustomField>
    <fullName>Application_Source__c</fullName>
    <label>Application Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ApplicationSource</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Federal_Tax_Id__c.field-meta.xml
<CustomField>
    <fullName>Federal_Tax_Id__c</fullName>
    <label>Federal Tax Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/ApplicationSource.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Community</fullName>
    </customValue>
    <customValue>
        <fullName>Webhook</fullName>
    </customValue>
    <customValue>
        <fullName>Web</fullName>
        <isActive>false</isActive>
        <label>Web</label>
    </customValue>
    <masterLabel>Application Source</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/LeadFactory.cls
@IsTest
public with sharing class LeadFactory {
    public static Lead create ( Lead lead ) {
        insert lead;
        return lead;
    }
    public static Lead create ( String companyName, String federalTaxId, String firstName, String lastName, String applicationSource ) {
        return create ( build( companyName, federalTaxId, firstName, lastName, applicationSource ) );
    }

    public static Lead build ( String companyName, String federalTaxId, String firstName, String lastName, String applicationSource ) {
        return new Lead (
            Company = companyName,
            Federal_Tax_Id__c = federalTaxId,
            FirstName = firstName,
            LastName = lastName,
            Application_Source__c = applicationSource
        );
    }
}